version: "3"
services:
#    accounting:
#        image: accounting:latest
#        build: ./.docker/tomcat
#        #command: ["sleep", "365d"]
#        working_dir: /accounting_app
#        volumes:
#            - ".:/accounting_app"
#        ports:
#          - "8080:8080"
#        depends_on:
#            - db

    db:
        image: postgres:9.6.my
        build: ./.docker/postgres
        ports:
          - "6666:5432"
        volumes:
            - "dbdata:/var/lib/postgresql/data"

volumes:
    dbdata: